name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      # ---------- Backend ----------
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: "Installing backend Dependencies"
        working-directory: api
        run: npm i


      - name: "Build Backend command"
        working-directory: api
        run: npm run build
      

      # ---------- Frontend ----------
      - name: Use Node.js ${{ matrix.node-version }} for frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
        
      - name: "Installing Frontend Dependencies"
        working-directory: frontend
        run: npm i


      - name: "Build frontend command"
        working-directory: api
        run: npm run build

